### Simular formulario de loggeo.
POST http://localhost:1234/auth
Content-Type: application/json

    {
        "nombre_usuario": "juan.perez",
        "password": "juan123"
    }

### Obtencion de todos los Usuarios.
GET http://localhost:1234/usuarios

### Obtencion de todos los Administradores.
GET http://localhost:1234/administradores
Authorization: Bearer

### Obtencion de todos los Proveedores.
GET http://localhost:1234/proveedores
Authorization: Bearer

### Obtencion de todos los Clientes.
GET http://localhost:1234/clientes
Authorization: Bearer

### Obtencion de todos los Productos.
GET http://localhost:1234/productos

### Obtencion de todos los Carritos.
GET http://localhost:1234/carritos
Authorization: Bearer

### Obtencion de todas las Ventas.
GET http://localhost:1234/ventas
Authorization: Bearer

### Obtencion de los datos de un Usuario en particular segun su id.
GET http://localhost:1234/usuarios/2
Authorization: Bearer

### Obtencion de los datos de un Administrador en particular segun su id.
GET http://localhost:1234/administradores/7
Authorization: Bearer

### Obtencion de los datos de un Proveedor en particular segun su id.
GET http://localhost:1234/proveedores/5
Authorization: Bearer

### Obtencion de los datos de un Cliente en particular segun su id.
GET http://localhost:1234/clientes/1
Authorization: Bearer

### Obtencion de los datos de un Producto en particular segun su id.
GET http://localhost:1234/productos/1

### Obtencion de los datos de un Carrito en particular segun su id.
GET http://localhost:1234/carritos/1
Authorization: Bearer

### Obtencion de los datos de una Venta en particular segun su id.
GET http://localhost:1234/ventas/1
Authorization: Bearer

### Crear un nuevo USUARIO-ADMINISTRADOR
POST http://localhost:1234/usuarios/administrador
Content-Type: application/json
Authorization: Bearer

{
  "nombre_usuario": "antonela.sosa",
  "password": "antonela123",
  "nombre": "Antonela",
  "apellido": "Sosa",
  "email": "antonela.sosa@example.com",
  "telefono": 123456789
}

### Crear un nuevo USUARIO-PROVEEDOR
POST http://localhost:1234/usuarios/proveedor
Content-Type: application/json
Authorization: Bearer

{
  "nombre_usuario": "distribuidora.cholita",
  "password": "cholita123",
  "razon_social": "Distribuidora Cholita",
  "email": "distribuidora.cholita@example.com",
  "telefono": "11223111",
  "cuit": "20199182",
  "calle": "De la Prieta",
  "nro": 3211,
  "ciudad": "Santa Fe"
}

#### Crear un nuevo USUARIO-CLIENTE
POST http://localhost:1234/usuarios/cliente
Content-Type: application/json

{
  "nombre_usuario": "marcos.acosta",
  "password": "marcos123",
  "nombre": "Marcos",
  "apellido": "Acosta",
  "email": "marcos.acosta@example.com",
  "telefono": 123456789,
  "dni": 3234678,
  "calle": "Zelarrayan",
  "nro": 123,
  "ciudad": "Zarate"
}

### Crear un nuevo Producto.

POST http://localhost:1234/productos
Content-Type: application/json
Authorization: Bearer

{
    "nombre_producto": "Transistor lgaa2",
    "precio": 1720,
    "stock": 36,
    "id_proveedor": 5
}

### Crear un nuevo Carrito y Venta.
POST http://localhost:1234/carrito
Content-Type: application/json

{
  "id_cliente": 1,
  "productos": [
    { "id_producto": 1, "cantidad": 3 },
    { "id_producto": 2, "cantidad": 2 }
  ]
}

###  Modificar algun atributo de usuario segun su id.
PATCH http://localhost:1234/usuarios/1
Content-Type: application/json
Authorization: Bearer

{
    "nombre_usuario": "miguel.carrera"
}

### Modificar el stock de un producto.
PATCH http://localhost:1234/aumentarStock
Content-Type: application/json
Authorization: Bearer

{
    "id_producto": 1,
    "aumentarStock": 30
}

### Eliminar un usuario de la base de datos segun su id.
DELETE http://localhost:1234/usuarios/10
Authorization: Bearer
